[
  { name: 'A Fan of Miyamoto', image: 'miyamotofan.gif' },
  { name: 'A Monkey in an Egg', image: 'monkeyegg.gif' },
  { name: 'Agent Sprout', image: 'agentsprout.gif' },
  { name: 'Alex Garland L', image: 'alexgarland.gif' },
  { name: 'Alex Garland R', image: 'alexgarlandr.gif' },
  { name: 'Anteater L', image: 'anteater1.gif' },
  { name: 'Anteater R', image: 'anteater1r.gif' },
  { name: 'Batman 1', image: 'batman1.gif' },
  { name: 'Batman 2', image: 'batman2.gif' },
  { name: 'Bats', image: 'bats.gif' },
  { name: 'Bearded Woman L', image: 'beardedwoman.gif' },
  { name: 'Bearded Woman R', image: 'beardedwomanr.gif' },
  { name: 'Beast L', image: 'beast.gif' },
  { name: 'Beast R', image: 'beastr.gif' },
  { name: 'Bill Gates', image: 'billgates.gif' },
  { name: 'Bin', image: 'bin.gif' },
  { name: 'Bins', image: 'bins.gif' },
  { name: 'Bjork', image: 'bjork.gif' },
  { name: 'Blue Horse Thing L', image: 'bluehorsething.gif' },
  { name: 'Blue Horse Thing R', image: 'bluehorsethingr.gif' },
  { name: 'Bob Sweezely', image: 'bobsweezely.gif' },
  { name: 'Bottingham L', image: 'bottingham.gif' },
  { name: 'Bottingham R', image: 'bottinghamr.gif' },
  { name: 'Bryan Adams L', image: 'bryanadams.gif' },
  { name: 'Bryan Adams R', image: 'bryanadamsr.gif' },
  { name: 'Butch Jenkins', image: 'butchjenkins.gif' },
  { name: 'Buzz Aldrin L', image: 'buzzaldrin.gif' },
  { name: 'Buzz Aldrin R', image: 'buzzaldrinr.gif' },
  { name: 'Captain Birdseye', image: 'captainbirdseye.gif' },
  { name: 'Chester Fisho 1 L', image: 'chesterfisho1.gif' },
  { name: 'Chester Fisho 1 R', image: 'chesterfisho1r.gif' },
  { name: 'Chester Fisho 2 L', image: 'chesterfisho2.gif' },
  { name: 'Chester Fisho 2 R', image: 'chesterfisho2r.gif' },
  { name: 'Chewbacca', image: 'chewbacca.gif' },
  { name: 'Cockney Div', image: 'cockneydiv.gif' },
  { name: 'Councillor Clack L', image: 'councillorclack.gif' },
  { name: 'Councillor Clack R', image: 'councillorclackr.gif' },
  { name: 'Crab L', image: 'crab.gif' },
  { name: 'Crab R', image: 'crabr.gif' },
  {
    name: 'Creature from the Brown Lagoon L',
    image: 'creaturefromthebrownlagoon.gif',
  },
  {
    name: 'Creature from the Brown Lagoon R',
    image: 'creaturefromthebrownlagoonr.gif',
  },
  { name: 'Daddy Cool 1', image: 'daddycool1.gif' },
  { name: 'Daddy Cool 2', image: 'daddycool2.gif' },
  { name: 'Daddy Cool 3', image: 'daddycool3.gif' },
  { name: 'Darth Ronson', image: 'darthronson.gif' },
  { name: 'Dead Mario L', image: 'deadmario.gif' },
  { name: 'Dead Mario R', image: 'deadmarior.gif' },
  { name: 'Dennis Man of Zinc L', image: 'dennismanofzinc.gif' },
  { name: 'Dennis Man of Zinc R', image: 'dennismanofzincr.gif' },
  { name: 'Distracted Mike L', image: 'distractedmike.gif' },
  { name: 'Distracted Mike R', image: 'distractedmiker.gif' },
  { name: 'Don Palmer', image: 'donpalmer.gif' },
  { name: 'Donny Rich', image: 'donnyrich.gif' },
  { name: 'Dot Cotton', image: 'dotcotton.gif' },
  { name: 'Dr Heinous 1', image: 'drheinous1.gif' },
  { name: 'Dr Heinous 2', image: 'drheinous2.gif' },
  { name: 'Dr Heinous 3', image: 'drheinous3.gif' },
  { name: 'Dr Heinous\'s Servant 1', image: 'drheinous\'sservant1.gif' },
  { name: 'Dr Heinous\'s Servant 2', image: 'drheinous\'sservant2.gif' },
  { name: 'Dr Trivia L', image: 'drtrivia.gif' },
  { name: 'Dr Trivia R', image: 'drtriviar.gif' },
  { name: 'Duck L', image: 'duck.gif' },
  { name: 'Duck R', image: 'duckr.gif' },
  { name: 'Duck Walking Backwards 1 L', image: 'duckwalkingbackwards1.gif' },
  { name: 'Duck Walking Backwards 1 R', image: 'duckwalkingbackwards1r.gif' },
  { name: 'Duck Walking Backwards 2 L', image: 'duckwalkingbackwards2.gif' },
  { name: 'Duck Walking Backwards 2 R', image: 'duckwalkingbackwards2r.gif' },
  { name: 'Easter Bunny', image: 'easterbunny.gif' },
  { name: 'Edward Lear 1 L', image: 'edwardlear1.gif' },
  { name: 'Edward Lear 1 R', image: 'edwardlear1r.gif' },
  { name: 'Edward Lear 2', image: 'edwardlear2.gif' },
  { name: 'Edward Lear 3', image: 'edwardlear3.gif' },
  { name: 'Edward Lear 4', image: 'edwardlear4.gif' },
  { name: 'Edward Lear 5', image: 'edwardlear5.gif' },
  { name: 'Enigmatic Pete', image: 'enigmaticpete.gif' },
  { name: 'Evil Samaritan', image: 'evilsamaritan.gif' },
  { name: 'Explosion', image: 'explosion.gif' },
  { name: 'Fat Sow L', image: 'fatsow.gif' },
  { name: 'Fat Sow R', image: 'fatsowr.gif' },
  { name: 'Fighter 1 L', image: 'fighter1.gif' },
  { name: 'Fighter 1 R', image: 'fighter1r.gif' },
  { name: 'Fighter 2', image: 'fighter2.gif' },
  { name: 'Fighter 3 L', image: 'fighter3.gif' },
  { name: 'Fighter 3 R', image: 'fighter3r.gif' },
  { name: 'Foynt L', image: 'foynt.gif' },
  { name: 'Foynt R', image: 'foyntr.gif' },
  { name: 'Gary Lineker', image: 'garylineker.gif' },
  { name: 'GaryBarlow L', image: 'garybarlow.gif' },
  { name: 'GaryBarlow R', image: 'garybarlowr.gif' },
  { name: 'Gilliam II L', image: 'gilliamii.gif' },
  { name: 'Gilliam II R', image: 'gilliamiir.gif' },
  { name: 'Giraffe Cat L', image: 'giraffecat.gif' },
  { name: 'Giraffe Cat R', image: 'giraffecatr.gif' },
  { name: 'Gossi The Dog 1 L', image: 'gossithedog1.gif' },
  { name: 'Gossi The Dog 1 R', image: 'gossithedog1r.gif' },
  { name: 'Gossi The Dog 2 L', image: 'gossithedog2.gif' },
  { name: 'Gossi The Dog 2 R', image: 'gossithedog2r.gif' },
  { name: 'Green Horse Thing L', image: 'greenhorsething.gif' },
  { name: 'Green Horse Thing R', image: 'greenhorsethingr.gif' },
  { name: 'Grn Mchl', image: 'grnmchl.gif' },
  { name: 'Guy 1', image: 'guy1.gif' },
  { name: 'Guy 2', image: 'guy2.gif' },
  { name: 'Guy 3 L', image: 'guy3.gif' },
  { name: 'Guy 3 R', image: 'guy3r.gif' },
  { name: 'Guy 4', image: 'guy4.gif' },
  { name: 'Guy 5', image: 'guy5.gif' },
  { name: 'Harris', image: 'harris.gif' },
  { name: 'Head 1', image: 'head1.gif' },
  { name: 'Head 2 L', image: 'head2.gif' },
  { name: 'Head 2 R', image: 'head2r.gif' },
  { name: 'Hedgehog 1 L', image: 'hedgehog1.gif' },
  { name: 'Hedgehog 1 R', image: 'hedgehog1r.gif' },
  { name: 'Hedgehog 2 L', image: 'hedgehog2.gif' },
  { name: 'Hedgehog 2 R', image: 'hedgehog2r.gif' },
  { name: 'Hunchback L', image: 'hunchback.gif' },
  { name: 'Hunchback R', image: 'hunchbackr.gif' },
  { name: 'Ian Beale', image: 'ianbeale.gif' },
  { name: 'Insincere Dave', image: 'insinceredave.gif' },
  { name: 'Inspector Sprout 1', image: 'inspectorsprout1.gif' },
  { name: 'Inspector Sprout 2', image: 'inspectorsprout2.gif' },
  { name: 'Insulin Guy L', image: 'insulinguy.gif' },
  { name: 'Insulin Guy R', image: 'insulinguyr.gif' },
  { name: 'Janine Butcher', image: 'janinebutcher.gif' },
  { name: 'Jar Jar Binks', image: 'jarjarbinks.gif' },
  { name: 'Krazy Snake L', image: 'krazysnake.gif' },
  { name: 'Krazy Snake R', image: 'krazysnaker.gif' },
  { name: 'Le Chef 1', image: 'lechef1.gif' },
  { name: 'Le Chef 2', image: 'lechef2.gif' },
  { name: 'Lewis 1', image: 'lewis1.gif' },
  { name: 'Lewis 2', image: 'lewis2.gif' },
  { name: 'Lewis 3', image: 'lewis3.gif' },
  { name: 'Lewis 4', image: 'lewis4.gif' },
  { name: 'Lewis 5', image: 'lewis5.gif' },
  { name: 'Lewis 6', image: 'lewis6.gif' },
  { name: 'Lex Luthor', image: 'lexluthor.gif' },
  { name: 'Magic Monkey', image: 'magicmonkey.gif' },
  { name: 'Megaman 6749', image: 'megaman6749.gif' },
  { name: 'Men Fighting L', image: 'menfighting.gif' },
  { name: 'Men Fighting R', image: 'menfightingr.gif' },
  { name: 'MFs Son L', image: 'mfsson.gif' },
  { name: 'MFs Son R', image: 'mfssonr.gif' },
  { name: 'Mona Lisa', image: 'monalisa.gif' },
  { name: 'Moomin 1 L', image: 'moomin1.gif' },
  { name: 'Moomin 1 R', image: 'moomin1r.gif' },
  { name: 'Moomin 2', image: 'moomin2.gif' },
  { name: 'Morrissey 1 L', image: 'morrissey1.gif' },
  { name: 'Morrissey 1 R', image: 'morrissey1r.gif' },
  { name: 'Morrissey 2 L', image: 'morrissey2.gif' },
  { name: 'Morrissey 2 R', image: 'morrissey2r.gif' },
  { name: 'Morse 01', image: 'morse1.gif' },
  { name: 'Morse 02', image: 'morse2.gif' },
  { name: 'Morse 03', image: 'morse3.gif' },
  { name: 'Morse 04', image: 'morse4.gif' },
  { name: 'Morse 05', image: 'morse5.gif' },
  { name: 'Morse 06', image: 'morse6.gif' },
  { name: 'Morse 07', image: 'morse7.gif' },
  { name: 'Morse 08', image: 'morse8.gif' },
  { name: 'Morse 09 L', image: 'morse9.gif' },
  { name: 'Morse 10 L', image: 'morse10.gif' },
  { name: 'Morse 10 R', image: 'morse10r.gif' },
  { name: 'Morse 11 L', image: 'morse11.gif' },
  { name: 'Morse 11 R', image: 'morse11r.gif' },
  { name: 'Mr Biffo L', image: 'unknown1.gif' },
  { name: 'Mr Biffo R', image: 'unknown1r.gif' },
  { name: 'Mr Big Ears L', image: 'mrbigears.gif' },
  { name: 'Mr Big Ears R', image: 'mrbigearsr.gif' },
  { name: 'Mr Big Nose', image: 'mrbignose.gif' },
  { name: 'Mr C L', image: 'mrc.gif' },
  { name: 'Mr C R', image: 'mrcr.gif' },
  { name: 'Mr Long Neck L', image: 'mrlongneck.gif' },
  { name: 'Mr Long Neck R', image: 'mrlongneckr.gif' },
  { name: 'Mr Nude L', image: 'mrnude.gif' },
  { name: 'Mr Nude R', image: 'mrnuder.gif' },
  { name: 'Mr Sunny 1', image: 'mrsunny1.gif' },
  { name: 'Mr Sunny 2', image: 'mrsunny2.gif' },
  { name: 'Mr Sunny 3 L', image: 'mrsunny3.gif' },
  { name: 'Mr Sunny 3 R', image: 'mrsunny3r.gif' },
  { name: 'Mr T 1', image: 'mrt1.gif' },
  { name: 'Mr T 2', image: 'mrt2.gif' },
  { name: 'Mr T 3', image: 'mrt3.gif' },
  { name: 'Mr Ts Manager', image: 'mrtsmanager.gif' },
  { name: 'Naked Psychiatrist L', image: 'nakedpsychiatrist.gif' },
  { name: 'Naked Psychiatrist R', image: 'nakedpsychiatristr.gif' },
  { name: 'Nightmare 1 L', image: 'nightmare1.gif' },
  { name: 'Nightmare 1 R', image: 'nightmare1r.gif' },
  { name: 'Nightmare 2 L', image: 'nightmare2.gif' },
  { name: 'Nightmare 2 R', image: 'nightmare2r.gif' },
  { name: 'Norton L', image: 'norton.gif' },
  { name: 'Norton R', image: 'nortonr.gif' },
  { name: 'Old Man L', image: 'oldman.gif' },
  { name: 'Old Man R', image: 'oldmanr.gif' },
  { name: 'Paranoia', image: 'paranoia.gif' },
  { name: 'Pat Walker', image: 'patwalker.gif' },
  { name: 'Phil Mitchell', image: 'philmitchell.gif' },
  { name: 'Phoning Honey 1', image: 'phoninghoney1.gif' },
  { name: 'Phoning Honey 2 L', image: 'phoninghoney2.gif' },
  { name: 'Phoning Honey 2 R', image: 'phoninghoney2r.gif' },
  { name: 'Picard', image: 'picard.gif' },
  { name: 'Poirot', image: 'poirot.gif' },
  { name: 'Rapping Shoe 1 L', image: 'rappingshoe1.gif' },
  { name: 'Rapping Shoe 1 R', image: 'rappingshoe1r.gif' },
  { name: 'Rapping Shoe 2 L', image: 'rappingshoe2.gif' },
  { name: 'Rapping Shoe 2 R', image: 'rappingshoe2r.gif' },
  { name: 'Red Horse Thing 1 L', image: 'redhorsething1.gif' },
  { name: 'Red Horse Thing 1 R', image: 'redhorsething1r.gif' },
  { name: 'Red Horse Thing 2 L', image: 'redhorsething2.gif' },
  { name: 'Red Horse Thing 2 R', image: 'redhorsething2r.gif' },
  { name: 'Relapse The Snake L', image: 'relapsethesnake.gif' },
  { name: 'Relapse The Snake R', image: 'relapsethesnaker.gif' },
  { name: 'Riker', image: 'riker.gif' },
  { name: 'Robert Smith', image: 'robertsmith.gif' },
  { name: 'Robin', image: 'robin.gif' },
  { name: 'Rollo Benny', image: 'rollobenny.gif' },
  { name: 'Roly L', image: 'roly.gif' },
  { name: 'Roly R', image: 'rolyr.gif' },
  { name: 'Rory Race', image: 'roryrace.gif' },
  { name: 'Roth Drakewind', image: 'rothdrakewind.gif' },
  { name: 'Rudolph L', image: 'rudolph.gif' },
  { name: 'Rudolph R', image: 'rudolphr.gif' },
  { name: 'S Arcasm', image: 'sarcasm.gif' },
  { name: 'Santa 1', image: 'santa1.gif' },
  { name: 'Santa 2', image: 'santa2.gif' },
  { name: 'Santa 3', image: 'santa3.gif' },
  { name: 'Sarah Michelle Gellar', image: 'sarahmichellegellar.gif' },
  { name: 'Schmuck L', image: 'schmuck.gif' },
  { name: 'Schmuck R', image: 'schmuckr.gif' },
  { name: 'Shark L', image: 'shark.gif' },
  { name: 'Shark R', image: 'sharkr.gif' },
  { name: 'Shigeru Miyamoto L', image: 'shigerumiyamoto.gif' },
  { name: 'Shigeru Miyamoto R', image: 'shigerumiyamotor.gif' },
  { name: 'Skellington', image: 'skellington.gif' },
  { name: 'Smilin Peter 1 L', image: 'smilinpeter1.gif' },
  { name: 'Smilin Peter 1 R', image: 'smilinpeter1r.gif' },
  { name: 'Smilin Peter 2 L', image: 'smilinpeter2.gif' },
  { name: 'Smilin Peter 2 R', image: 'smilinpeter2r.gif' },
  { name: 'Smilin Peter 3 L', image: 'smilinpeter3.gif' },
  { name: 'Smilin Peter 3 R', image: 'smilinpeter3r.gif' },
  { name: 'Snowman', image: 'snowman.gif' },
  { name: 'Socky The Sock Puppet L', image: 'sockythesockpuppet.gif' },
  { name: 'Socky The Sock Puppet R', image: 'sockythesockpuppetr.gif' },
  { name: 'Sooty', image: 'sooty.gif' },
  { name: 'Spock L', image: 'spock.gif' },
  { name: 'Spock R', image: 'spockr.gif' },
  { name: 'Stanley Rat', image: 'stanleyrat.gif' },
  { name: 'Steve Owen', image: 'steveowen.gif' },
  { name: 'Stevie Wonder', image: 'steviewonder.gif' },
  { name: 'Strangelove The Tramp', image: 'strangelovethetramp.gif' },
  { name: 'Stuart Campbell', image: 'stuartcampbell.gif' },
  { name: 'Sweep', image: 'sweep.gif' },
  { name: 'The Devil', image: 'thedevil.gif' },
  { name: 'The Digitiser Donkey', image: 'thedigitiserdonkey.gif' },
  { name: 'The Fifth TeleTubby', image: 'thefifthteletubby.gif' },
  { name: 'The Funny Dancers L', image: 'thefunnydancers.gif' },
  { name: 'The Funny Dancers R', image: 'thefunnydancersr.gif' },
  { name: 'The Man 1', image: 'theman1.gif' },
  { name: 'The Man 2', image: 'theman2.gif' },
  { name: 'The Man 3', image: 'theman3.gif' },
  { name: 'The Man 4', image: 'theman4.gif' },
  { name: 'The Mans Daddy', image: 'themansdaddy.gif' },
  { name: 'The Snakes 01 R', image: 'thesnakes1r.gif' },
  { name: 'The Snakes 01 R', image: 'thesnakes1r.gif' },
  { name: 'The Snakes 02 L', image: 'thesnakes2.gif' },
  { name: 'The Snakes 02 R', image: 'thesnakes2r.gif' },
  { name: 'The Snakes 03 L', image: 'thesnakes3.gif' },
  { name: 'The Snakes 03 R', image: 'thesnakes3r.gif' },
  { name: 'The Snakes 04 L', image: 'thesnakes4.gif' },
  { name: 'The Snakes 04 R', image: 'thesnakes4r.gif' },
  { name: 'The Snakes 05 L', image: 'thesnakes5.gif' },
  { name: 'The Snakes 05 R', image: 'thesnakes5r.gif' },
  { name: 'The Snakes 06 L', image: 'thesnakes6.gif' },
  { name: 'The Snakes 06 R', image: 'thesnakes6r.gif' },
  { name: 'The Snakes 07 L', image: 'thesnakes7.gif' },
  { name: 'The Snakes 07 R', image: 'thesnakes7r.gif' },
  { name: 'The Snakes 08 L', image: 'thesnakes8.gif' },
  { name: 'The Snakes 08 R', image: 'thesnakes8r.gif' },
  { name: 'The Snakes 09 L', image: 'thesnakes9.gif' },
  { name: 'The Snakes 09 R', image: 'thesnakes9r.gif' },
  { name: 'The Snakes 10 L', image: 'thesnakes10.gif' },
  { name: 'The Snakes 10 R', image: 'thesnakes10r.gif' },
  { name: 'The Snakes 11 L', image: 'thesnakes11.gif' },
  { name: 'The Snakes 11 R', image: 'thesnakes11r.gif' },
  { name: 'The Snakes 12 L', image: 'thesnakes12.gif' },
  { name: 'The Snakes 12 R', image: 'thesnakes12r.gif' },
  { name: 'The Snakes 13 L', image: 'thesnakes13.gif' },
  { name: 'The Snakes 13 R', image: 'thesnakes13r.gif' },
  { name: 'The Snakes 14 L', image: 'thesnakes14.gif' },
  { name: 'The Snakes 14 R', image: 'thesnakes14r.gif' },
  { name: 'The Snakes 15 L', image: 'thesnakes15.gif' },
  { name: 'The Snakes 15 R', image: 'thesnakes15r.gif' },
  { name: 'The Snakes 16 L', image: 'thesnakes16.gif' },
  { name: 'The Snakes 16 R', image: 'thesnakes16r.gif' },
  { name: 'The Snakes 17 L', image: 'thesnakes17.gif' },
  { name: 'The Snakes 17 R', image: 'thesnakes17r.gif' },
  { name: 'The Snakes 18 L', image: 'thesnakes18.gif' },
  { name: 'The Snakes 18 R', image: 'thesnakes18r.gif' },
  { name: 'The Snakes 19 L', image: 'thesnakes19.gif' },
  { name: 'The Snakes 19 R', image: 'thesnakes19r.gif' },
  { name: 'The Snakes 20 L', image: 'thesnakes20.gif' },
  { name: 'The Snakes 20 R', image: 'thesnakes20r.gif' },
  { name: 'The Snakes 21 L', image: 'thesnakes21.gif' },
  { name: 'The Snakes 21 R', image: 'thesnakes21r.gif' },
  { name: 'The Snakes 22 L', image: 'thesnakes22.gif' },
  { name: 'The Snakes 22 R', image: 'thesnakes22r.gif' },
  { name: 'The Snakes 23 L', image: 'thesnakes23.gif' },
  { name: 'The Snakes 23 R', image: 'thesnakes23r.gif' },
  { name: 'The Snakes 24 L', image: 'thesnakes24.gif' },
  { name: 'The Snakes 24 R', image: 'thesnakes24r.gif' },
  { name: 'The Snakes 25 L', image: 'thesnakes25.gif' },
  { name: 'The Snakes 25 R', image: 'thesnakes25r.gif' },
  { name: 'The Snakes 26 L', image: 'thesnakes26.gif' },
  { name: 'The Snakes 26 R', image: 'thesnakes26r.gif' },
  { name: 'The Snakes 27 L', image: 'thesnakes27.gif' },
  { name: 'The Snakes 27 R', image: 'thesnakes27r.gif' },
  { name: 'The Snakes 28 L', image: 'thesnakes28.gif' },
  { name: 'The Snakes 28 R', image: 'thesnakes28r.gif' },
  { name: 'The Snakes 29 L', image: 'thesnakes29.gif' },
  { name: 'The Snakes 29 R', image: 'thesnakes29r.gif' },
  { name: 'The Snakes 30 L', image: 'thesnakes30.gif' },
  { name: 'The Snakes 30 R', image: 'thesnakes30r.gif' },
  { name: 'The Snakes 31 L', image: 'thesnakes31.gif' },
  { name: 'The Snakes 31 R', image: 'thesnakes31r.gif' },
  { name: 'The Snakes 32 L', image: 'thesnakes32.gif' },
  { name: 'The Snakes 32 R', image: 'thesnakes32r.gif' },
  { name: 'The Snakes 33 L', image: 'thesnakes33.gif' },
  { name: 'The Snakes 33 R', image: 'thesnakes33r.gif' },
  { name: 'The Snakes 34 L', image: 'thesnakes34.gif' },
  { name: 'The Snakes 34 R', image: 'thesnakes34r.gif' },
  { name: 'The Snakes 35 L', image: 'thesnakes35.gif' },
  { name: 'The Snakes 35 R', image: 'thesnakes35r.gif' },
  { name: 'The Snakes 36 L', image: 'thesnakes36.gif' },
  { name: 'The Snakes 36 R', image: 'thesnakes36r.gif' },
  { name: 'The Snakes 37 L', image: 'thesnakes37.gif' },
  { name: 'The Snakes 37 R', image: 'thesnakes37r.gif' },
  { name: 'The Snakes 38 L', image: 'thesnakes38.gif' },
  { name: 'The Snakes 38 R', image: 'thesnakes38r.gif' },
  { name: 'The Snakes 39 L', image: 'thesnakes39.gif' },
  { name: 'The Snakes 39 R', image: 'thesnakes39r.gif' },
  { name: 'The Snakes 40 L', image: 'thesnakes40.gif' },
  { name: 'The Snakes 40 R', image: 'thesnakes40r.gif' },
  { name: 'The Snakes 41 L', image: 'thesnakes41.gif' },
  { name: 'The Snakes 41 R', image: 'thesnakes41r.gif' },
  { name: 'The Snakes 42 L', image: 'thesnakes42.gif' },
  { name: 'The Snakes 42 R', image: 'thesnakes42r.gif' },
  { name: 'The Snakes 43 L', image: 'thesnakes43.gif' },
  { name: 'The Snakes 43 R', image: 'thesnakes43r.gif' },
  { name: 'The Snakes 44 L', image: 'thesnakes44.gif' },
  { name: 'The Snakes 44 R', image: 'thesnakes44r.gif' },
  { name: 'The Snakes 45 L', image: 'thesnakes45.gif' },
  { name: 'The Snakes 45 R', image: 'thesnakes45r.gif' },
  { name: 'The Snakes 46 L', image: 'thesnakes46.gif' },
  { name: 'The Snakes 46 R', image: 'thesnakes46r.gif' },
  { name: 'The Snakes 47 L', image: 'thesnakes47.gif' },
  { name: 'The Snakes 47 R', image: 'thesnakes47r.gif' },
  { name: 'The Snakes 48 L', image: 'thesnakes48.gif' },
  { name: 'The Snakes 48 R', image: 'thesnakes48r.gif' },
  { name: 'The Snakes 49 L', image: 'thesnakes49.gif' },
  { name: 'The Snakes 49 R', image: 'thesnakes49r.gif' },
  { name: 'The Snakes 50 L', image: 'thesnakes50.gif' },
  { name: 'The Snakes 50 R', image: 'thesnakes50r.gif' },
  { name: 'The Snakes 51 L', image: 'thesnakes51.gif' },
  { name: 'The Snakes 51 R', image: 'thesnakes51r.gif' },
  { name: 'The Snakes 52 L', image: 'thesnakes52.gif' },
  { name: 'The Snakes 52 R', image: 'thesnakes52r.gif' },
  { name: 'The Snakes 53 L', image: 'thesnakes53.gif' },
  { name: 'The Snakes 53 R', image: 'thesnakes53r.gif' },
  { name: 'The Sun 1', image: 'thesun1.gif' },
  { name: 'The Worst Thing Ever L', image: 'theworstthingever.gif' },
  { name: 'The Worst Thing Ever R', image: 'theworstthingeverr.gif' },
  { name: 'Thing 1 L', image: 'thing1.gif' },
  { name: 'Thing 1 R', image: 'thing1r.gif' },
  { name: 'Thing 2', image: 'thing2.gif' },
  { name: 'Thing 3', image: 'thing3.gif' },
  { name: 'Thing 4 L', image: 'thing4.gif' },
  { name: 'Thing 4 R', image: 'thing4r.gif' },
  { name: 'Thinny Facer', image: 'thinnyfacer.gif' },
  { name: 'Thom Yorke', image: 'thomyorke.gif' },
  { name: 'Tin Man 1 L', image: 'tinman1.gif' },
  { name: 'Tin Man 1 R', image: 'tinman1r.gif' },
  { name: 'Tin Man 2 L', image: 'tinman2.gif' },
  { name: 'Tin Man 2 R', image: 'tinman2r.gif' },
  { name: 'Tony Mott', image: 'tonymott.gif' },
  { name: 'Tooth Fairy', image: 'toothfairy.gif' },
  { name: 'Tot L', image: 'tot.gif' },
  { name: 'Tot R', image: 'totr.gif' },
  { name: 'Toynbee L', image: 'toynbee.gif' },
  { name: 'Toynbee R', image: 'toynbeer.gif' },
  { name: 'Turner The Worm 1 L', image: 'turnertheworm1.gif' },
  { name: 'Turner The Worm 1 R', image: 'turnertheworm1r.gif' },
  { name: 'Turner The Worm 2 L', image: 'turnertheworm2.gif' },
  { name: 'Turner The Worm 2 R', image: 'turnertheworm2r.gif' },
  { name: 'Unknown 1', image: 'unknown1.gif' },
  { name: 'Unknown 2 L', image: 'unknown2.gif' },
  { name: 'Unknown 2 R', image: 'unknown2r.gif' },
  { name: 'Unknown 3', image: 'unknown3.gif' },
  { name: 'Unknown 4', image: 'unknown4.gif' },
  { name: 'Valentine Rusk', image: 'valentinerusk.gif' },
  { name: 'Violet Berlin', image: 'violetberlin.gif' },
  { name: 'Wasp 1 L', image: 'wasp1.gif' },
  { name: 'Wasp 1 R', image: 'wasp1r.gif' },
  { name: 'Wasp 2 L', image: 'wasp2.gif' },
  { name: 'Wasp 2 R', image: 'wasp2r.gif' },
  { name: 'Wasp 3 L', image: 'wasp3.gif' },
  { name: 'Wasp 3 R', image: 'wasp3r.gif' },
  { name: 'Wasp 4 L', image: 'wasp4.gif' },
  { name: 'Wasp 4 R', image: 'wasp4r.gif' },
  { name: 'Wasp 5 L', image: 'wasp5.gif' },
  { name: 'Wasp 5 R', image: 'wasp5r.gif' },
  { name: 'Wasp 6 L', image: 'wasp6.gif' },
  { name: 'Wasp 6 R', image: 'wasp6r.gif' },
  { name: 'Wired Child', image: 'wiredchild.gif' },
  { name: 'Working Class Thug L', image: 'workingclassthug.gif' },
  { name: 'Working Class Thug R', image: 'workingclassthugr.gif' },
  { name: 'Yellow Dave', image: 'yellowdave.gif' },
  { name: 'Yellow Horse Thing L', image: 'yellowhorsething.gif' },
  { name: 'Yellow Horse Thing R', image: 'yellowhorsethingr.gif' },
  { name: 'Yellow Samuel L', image: 'yellowsamuel.gif' },
  { name: 'Yellow Samuel R', image: 'yellowsamuelr.gif' },
  { name: 'Yoda 1 L', image: 'yoda1.gif' },
  { name: 'Yoda 1 R', image: 'yoda1r.gif' },
  { name: 'Yoda 2', image: 'yoda2.gif' },
  { name: 'Zombie Dave 1 L', image: 'zombiedave1.gif' },
  { name: 'Zombie Dave 1 R', image: 'zombiedave1r.gif' },
  { name: 'Zombie Dave 2', image: 'zombiedave2.gif' },
];
